// MongoDB Setup Script for Staff Members
// Run this in MongoDB Compass or mongosh console
// Database: medifeedback
// Collection: staffs

db.staffs.insertMany([
  {
    staffId: "STF001",
    name: "Dr. Rajesh Kumar",
    role: "Doctor",
    department: "Emergency",
    specialization: "Emergency Medicine",
    email: "rajesh.kumar@hospital.com",
    phone: "+91-9876543210",
    avatar: "https://i.pravatar.cc/150?img=1",
    totalFeedbackCount: 0,
    averageRating: 0,
    positiveCount: 0,
    neutralCount: 0,
    negativeCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    staffId: "STF002",
    name: "Dr. Priya Singh",
    role: "Doctor",
    department: "OPD",
    specialization: "General Medicine",
    email: "priya.singh@hospital.com",
    phone: "+91-9876543211",
    avatar: "https://i.pravatar.cc/150?img=2",
    totalFeedbackCount: 0,
    averageRating: 0,
    positiveCount: 0,
    neutralCount: 0,
    negativeCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    staffId: "STF003",
    name: "Dr. Amitabh Verma",
    role: "Doctor",
    department: "Surgery",
    specialization: "General Surgery",
    email: "amitabh.verma@hospital.com",
    phone: "+91-9876543212",
    avatar: "https://i.pravatar.cc/150?img=3",
    totalFeedbackCount: 0,
    averageRating: 0,
    positiveCount: 0,
    neutralCount: 0,
    negativeCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    staffId: "STF004",
    name: "Dr. Neha Patel",
    role: "Doctor",
    department: "IPD",
    specialization: "Internal Medicine",
    email: "neha.patel@hospital.com",
    phone: "+91-9876543213",
    avatar: "https://i.pravatar.cc/150?img=4",
    totalFeedbackCount: 0,
    averageRating: 0,
    positiveCount: 0,
    neutralCount: 0,
    negativeCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    staffId: "STF005",
    name: "Dr. Vikram Desai",
    role: "Doctor",
    department: "Radiology",
    specialization: "Diagnostic Imaging",
    email: "vikram.desai@hospital.com",
    phone: "+91-9876543214",
    avatar: "https://i.pravatar.cc/150?img=5",
    totalFeedbackCount: 0,
    averageRating: 0,
    positiveCount: 0,
    neutralCount: 0,
    negativeCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    staffId: "STF006",
    name: "Sister Ananya Das",
    role: "Nurse",
    department: "Emergency",
    specialization: "Emergency Nursing",
    email: "ananya.das@hospital.com",
    phone: "+91-9876543215",
    avatar: "https://i.pravatar.cc/150?img=6",
    totalFeedbackCount: 0,
    averageRating: 0,
    positiveCount: 0,
    neutralCount: 0,
    negativeCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    staffId: "STF007",
    name: "Nurse Priya Sharma",
    role: "Nurse",
    department: "IPD",
    specialization: "ICU Nursing",
    email: "priya.sharma@hospital.com",
    phone: "+91-9876543216",
    avatar: "https://i.pravatar.cc/150?img=7",
    totalFeedbackCount: 0,
    averageRating: 0,
    positiveCount: 0,
    neutralCount: 0,
    negativeCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    staffId: "STF008",
    name: "Mr. Arjun Mehta",
    role: "Technician",
    department: "Laboratory",
    specialization: "Clinical Pathology",
    email: "arjun.mehta@hospital.com",
    phone: "+91-9876543217",
    avatar: "https://i.pravatar.cc/150?img=8",
    totalFeedbackCount: 0,
    averageRating: 0,
    positiveCount: 0,
    neutralCount: 0,
    negativeCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    staffId: "STF009",
    name: "Ms. Ritika Gupta",
    role: "Technician",
    department: "Radiology",
    specialization: "X-Ray & Ultrasound",
    email: "ritika.gupta@hospital.com",
    phone: "+91-9876543218",
    avatar: "https://i.pravatar.cc/150?img=9",
    totalFeedbackCount: 0,
    averageRating: 0,
    positiveCount: 0,
    neutralCount: 0,
    negativeCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    staffId: "STF010",
    name: "Dr. Anil Kapoor",
    role: "Doctor",
    department: "Pharmacy",
    specialization: "Clinical Pharmacy",
    email: "anil.kapoor@hospital.com",
    phone: "+91-9876543219",
    avatar: "https://i.pravatar.cc/150?img=10",
    totalFeedbackCount: 0,
    averageRating: 0,
    positiveCount: 0,
    neutralCount: 0,
    negativeCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    staffId: "STF011",
    name: "Mr. Suresh Rao",
    role: "Administrator",
    department: "General",
    specialization: "Hospital Administration",
    email: "suresh.rao@hospital.com",
    phone: "+91-9876543220",
    avatar: "https://i.pravatar.cc/150?img=11",
    totalFeedbackCount: 0,
    averageRating: 0,
    positiveCount: 0,
    neutralCount: 0,
    negativeCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    staffId: "STF012",
    name: "Dr. Pooja Iyer",
    role: "Doctor",
    department: "General",
    specialization: "General Practitioner",
    email: "pooja.iyer@hospital.com",
    phone: "+91-9876543221",
    avatar: "https://i.pravatar.cc/150?img=12",
    totalFeedbackCount: 0,
    averageRating: 0,
    positiveCount: 0,
    neutralCount: 0,
    negativeCount: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]);

// Verify the insert
db.staffs.find().pretty();
